default: &default

development:
  <<: *default
  http_triggers:
    page: http://localhost:3000/
    content: http://localhost:3000/

test:
  <<: *default

production:
  <<: *default
  http_triggers:
    page: http://page.x-history.top/
    content: http://content.x-history.top/
    visithistory: http://visithistory.x-history.top/

